# Check https://pre-commit.com/hooks.html for all available pre-commit hooks

exclude: '^docs/conf.py'

default_language_version:
    python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
    exclude: ^.vscode/
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  # - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows


- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    language_version: python3

## If like to embrace black styles even in the docs:
# - repo: https://github.com/asottile/blacken-docs
#   rev: v1.12.0
#   hooks:
#   - id: blacken-docs
#     additional_dependencies: [black]

- repo: https://github.com/pycqa/pylint
  rev: v2.15.5
  hooks:
  - id: pylint
    additional_dependencies: [anytree, packaging, defusedxml]
    exclude:
      ^tests/

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.982
  hooks:
    - id: mypy
      exclude:
        ^tests/
      args: [--strict, --ignore-missing-imports]
      additional_dependencies: [packaging, defusedxml]

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      exclude: ^tests/
